OCTO-10853-dockerize tests
pbs/pycaption pull request #310
Opened 2023-10-25 07:15 UTC by OlteanuRares

2023-10-25 07:20 UTC, OlteanuRares commented
this works by running ./run_tests <test python version> (test_py37, test_py38., test_py39) if none provided will default to test_py39
also works with docker compose up <test python version>

2023-10-27 08:08 UTC, lorandvarga requested changes

2023-10-27 10:33 UTC, lorandvarga requested changes

2023-10-27 10:33 UTC, lorandvarga commented on docker-compose.yml
> +  db:
I don't think pycaption needs a db service.

2023-10-27 10:33 UTC, lorandvarga commented on test_requirements.txt
> +psycopg2-binary
probably psycopg2 is not necesarry here. I'd say we use the dependencies from tox.ini

2023-10-27 10:33 UTC, lorandvarga commented on docker-compose.yml
> +      pytest tests/ -vvvv --junitxml test_report.xml --cov=tests --cov-report xml:coverage.xml;
Should be taken from tox.ini

2023-10-27 10:33 UTC, lorandvarga commented on docker-compose.yml
> +volumes:
We probably don't need any volumes

2023-10-27 10:33 UTC, lorandvarga commented on docker-compose.yml
> +    driver: local
We should add python 3.10 as in tox.ini

2023-10-31 11:48 UTC, lorandvarga requested changes

2023-10-31 11:48 UTC, lorandvarga commented on .github/workflows/main.yml
> +          ls -al
We can remove the ls -al and the |

2023-10-31 11:48 UTC, lorandvarga commented on .github/workflows/main.yml
>            sudo apt-get install -y --no-install-recommends libxml-xpath-perl
we can remove the ls -al

2023-10-31 11:48 UTC, lorandvarga commented on setup.py
> +    version='2.1.1.dev1',
We can remove the .dev1

2023-10-31 11:48 UTC, lorandvarga commented on docker-compose.yml
> +      pytest -vvvv --color=yes --junit-xml=junit.xml --cov=pycaption --cov-report xml:coverage.xml;
We should record the results as github artifacts if possible.
See https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

2023-10-31 11:50 UTC, lorandvarga requested changes

2023-10-31 11:50 UTC, lorandvarga commented on .github/workflows/main.yml
>      strategy:
Please rename main.yml into something more meaningful like unit_tests.yml

2023-10-31 13:34 UTC, lorandvarga approved these changes

2023-10-31 15:08 UTC, merged